baseURL = 'https://bunzing.org/'
languageCode = 'nl'
title = 'Ontdek wat er werkelijk achter NAVO schuilgaat | Bunzing'
description = 'De NAVO had om vrede moeten gaan. Maar wat gebeurde er werkelijk? Ontdek het allemaal.'
theme = ["flow-theme"]

[params]
mainSections = [ "posts" ]
facebook = "https://www.facebook.com/profile.php?id=61575103342803"
instagram =  "https://www.instagram.com/bunzingorg/"
linkedin = "https://www.linkedin.com/company/bunzing/"
# twitter = "@bunzing"
mastodon = "https://mstdn.social/@bunzing"
substack = "https://bunzing.substack.com"
spotify = "https://open.spotify.com/show/0lnivLTo5SVGLNvDmcCkYX"
youtube = "https://www.youtube.com/@BunzingOrgg"


opengraph_title = "NAVO: De keerzijde van een verdrag"
opengraph_sitename = "Bunzing"
opengraph_description = "De NAVO had om vrede moeten gaan. Maar wat gebeurde er werkelijk? Ontdek het allemaal."
opengraph_image = "media/opengraph.png"
opengraph_video = "media/navo.mp4"

[params.contact]
organisation = "Bunzing HK"
location = "Amsterdam, Nederland"
email = "hallo@bunzing.org"

  [params.author]
  name = "Bunzing"
  email = "hallo@bunzing.org"

  [params.podcast]
  title = "NAVO: De keerzijde van een verdrag"
  description = "De Noord-Atlantische Verdragsorganisatie (NAVO) had om vrede moeten gaan. Een verdrag ter verdediging. Om West-Europese en Amerikaanse levens veilig te stellen. Maar wat gebeurde er werkelijk? Ontdekt het allemaal."
  tagline = "Ontdek wat er werkelijk achter de NAVO schuilt"
  explicit = "false"
  download_url = "https://b.bunzing.org/"
  cdn_url = "https://b.bunzing.org/"
  itunes_url = "https://podcasts.apple.com/us/podcast/navo-de-keerzijde-van-een-verdrag/id1820276755"
  itunes_id = "id1820276755"
  cover_image = "navo-cover.png"
  copyright = "CC BY-NC-SA · 2025 Bunzing"

[outputFormats.aacfeed]
MediaType = "application/rss+xml"
BaseName = "index"
path = "/feed/aac"
IsHTML = false
IsPlainText = true
noUgly = true
Rel = "alternate"

[outputFormats.mp3feed]
MediaType = "application/rss+xml"
BaseName = "index"
path = "/feed/mp3"
IsHTML = false
IsPlainText = true
noUgly = true
Rel = "alternate"

[outputs]
home = [ "HTML", "AMP", "RSS", "aacfeed", "mp3feed" ]
