baseURL = 'https://example.org/'
languageCode = 'nl-nl'
title = 'Ontdek wat er werkelijk achter NAVO schuilgaat | Bunzing'
description = ''
theme = ["flow-theme"]


[params]
twitter = "@bunzing"
mainSections = [ "episodes" ]

  [params.author]
  name = "Bunzing"
  email = "hallo@bunzing.org"

  
  [params.podcast]
  title = "NAVO: De keerzijde van een verdrag"
  description = "De Noord-Atlantische Verdragsorganisatie (NAVO) had om vrede moeten gaan. Een verdrag ter verdediging. Om West-Europese en Amerikaanse levens veilig te stellen. Maar wat gebeurde er werkelijk?"
  tagline = "Ontdek wat er werkelijk achter de NAVO schuilt"
  download_url = "https://b.bunzing.org/"
  cdn_url = "https://b.bunzing.org/"
  itunes_url = "https://podcasts.apple.com/us/podcast/bunzing/id100000000"
  itunes_id = "id100000000"

[outputFormats.aacfeed]
MediaType = "application/rss+xml"
BaseName = "index"
path = "/feed/aac"
IsHTML = false
IsPlainText = true
noUgly = true
Rel = "alternate"

[outputFormats.mp3feed]
MediaType = "application/rss+xml"
BaseName = "index"
path = "/feed/mp3"
IsHTML = false
IsPlainText = true
noUgly = true
Rel = "alternate"

[outputs]
home = [ "HTML", "AMP", "RSS", "aacfeed", "mp3feed" ]

